Tarea6/Models/Formulario.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tarea6.Models
{
    public class Formulario
    {
        public int ID { get; set; }
        [Required]
        public string Cedula { get; set; }
        [Required]
        public string Nombre { get; set; }
        [Required]
        public string Apellido { get; set; }
        [Range(15,100,ErrorMessage ="Debe ser mayor de 15 años")]
        public int Edad { get; set; }
        public string Telefono { get; set; }
        [DataType(DataType.EmailAddress, ErrorMessage ="Debe ser una direccion de correo valida")]
        public string Correo { get; set; }
        public Genero Genero { get; set; }
        public string EstadoCivil { get; set; }
        public IList<string> HobbiesSeleccionados { get; set; }
        public string Hobbies { get; set; }
        [NotMapped]
        public IList<SelectListItem> HobbiesDisponibles { get; set; }

        public Formulario()
        {
            HobbiesSeleccionados = new List<string>();
            HobbiesDisponibles = new List<SelectListItem>();
        }
    }

    public enum Genero { Masculino , Femenino}
}

Tarea6/Models/FormularioContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using Tarea6.Models;

namespace Tarea6.DAL
{
    public class FormularioContext:DbContext
    {
        public FormularioContext() : base("FormularioContext") { }

        public DbSet<Formulario> Formularios { get; set; }
    }
}

Tarea6/Controllers/FormulariosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Tarea6.DAL;
using Tarea6.Models;

namespace Tarea6.Controllers
{
    public class FormulariosController : Controller
    {
        private FormularioContext db = new FormularioContext();

        // GET: Formularios
        public ActionResult Index()
        {
            return View(db.Formularios.ToList());
        }

        
        // GET: Formularios/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.Formularios.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // GET: Formularios/Create
        public ActionResult Create()
        {
            var model = new Formulario
            {
                HobbiesDisponibles = GetHobbies()
            };
            return View(model);
        }

        // POST: Formularios/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Cedula,Nombre,Apellido,Edad,Telefono,Correo,Genero,EstadoCivil,HobbiesSeleccionados")] Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                var hobbies = string.Join(", ", formulario.HobbiesSeleccionados);
                formulario.Hobbies = hobbies;
                db.Formularios.Add(formulario);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            formulario.HobbiesDisponibles = GetHobbies();
            return View(formulario);
        }
        
        private IList<SelectListItem> GetHobbies()
        {
            return new List<SelectListItem>
            {
                new SelectListItem{ Text = "Peliculas", Value = "Peliculas"},
                new SelectListItem{ Text = "Deportes", Value = "Deportes"},
                new SelectListItem{ Text = "Musica", Value = "Musica"},
                new SelectListItem{ Text = "Coleccionar", Value = "Coleccionar"},
            };
        }

        // GET: Formularios/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.Formularios.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Cedula,Nombre,Apellido,Edad,Telefono,Correo,Genero,EstadoCivil")] Formulario formulario)
        {
            if (ModelState.IsValid)
            {
                db.Entry(formulario).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(formulario);
        }

        // GET: Formularios/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Formulario formulario = db.Formularios.Find(id);
            if (formulario == null)
            {
                return HttpNotFound();
            }
            return View(formulario);
        }

        // POST: Formularios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Formulario formulario = db.Formularios.Find(id);
            db.Formularios.Remove(formulario);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Tarea6/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Tarea6.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Tarea6/Views/Formularios/Create.cshtml
@model Tarea6.Models.Formulario

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
	<h4>Formulario</h4>
	<hr />
	@Html.ValidationSummary(true, "", new { @class = "text-danger" })
	<div class="form-group">
		@Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
			@Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@Html.EnumDropDownListFor(model => model.Genero, htmlAttributes: new { @class = "form-control" })
			@Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.EstadoCivil, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			<label class="radio">@Html.RadioButtonFor(model => model.EstadoCivil, "Soltero") Soltero</label>
			<label class="radio">@Html.RadioButtonFor(model => model.EstadoCivil, "Casado") Casado</label>
			<label class="radio">@Html.RadioButtonFor(model => model.EstadoCivil, "Viudo") Viudo</label>
			<label class="radio"> @Html.RadioButtonFor(model => model.EstadoCivil, "Union Libre") Union Libre</label>

			@Html.ValidationMessageFor(model => model.EstadoCivil, "", new { @class = "text-danger" })
		</div>
	</div>

	<div class="form-group">
		@Html.LabelFor(model => model.Hobbies, htmlAttributes: new { @class = "control-label col-md-2" })
		<div class="col-md-10">
			@foreach(var item in Model.HobbiesDisponibles){
			<div class="checkbox">
				<label>
					<input type="checkbox" name="HobbiesSeleccionados" value="@item.Value" />@item.Text
					@*@Html.CheckBox("HobbiesSeleccionados", new { AttributeValue = item.Value }) @item.Text*@
				</label>
					</div>
					}
					@Html.ValidationMessageFor(model => model.Hobbies, "", new { @class = "text-danger" })
				</div>
			</div>

			<div class="form-group">
				<div class="col-md-offset-2 col-md-10">
					<input type="submit" value="Create" class="btn btn-default" />
				</div>
			</div>
		</div>
		}

		<div>
			@Html.ActionLink("Back to List", "Index")
		</div>

		@section Scripts {
			@Scripts.Render("~/bundles/jqueryval")
		}

Tarea6/Views/Formularios/Delete.cshtml
@model Tarea6.Models.Formulario

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Formulario</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Apellido)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Apellido)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Edad)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Edad)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Correo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Correo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Genero)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EstadoCivil)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tarea6/Views/Formularios/Details.cshtml
@model Tarea6.Models.Formulario

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Formulario</h4>
    <hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.Cedula)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Cedula)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Nombre)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Nombre)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Apellido)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Apellido)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Edad)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Edad)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Telefono)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Telefono)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Correo)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Correo)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Genero)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.Genero)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.EstadoCivil)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.EstadoCivil)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.Hobbies)
		</dt>
		<dd>
			@Html.DisplayFor(model => model.Hobbies)
		</dd>

	</dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Tarea6/Views/Formularios/Edit.cshtml
@model Tarea6.Models.Formulario

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Formulario</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Cedula, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cedula, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cedula, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Apellido, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Apellido, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Apellido, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Edad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Edad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Edad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Correo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Correo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Correo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Genero, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Genero, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Genero, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EstadoCivil, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EstadoCivil, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EstadoCivil, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tarea6/Views/Formularios/Index.cshtml
@model IEnumerable<Tarea6.Models.Formulario>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
	<tr>
		<th>
			@Html.DisplayNameFor(model => model.Cedula)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Nombre)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Apellido)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Edad)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Telefono)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Correo)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Genero)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.EstadoCivil)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.Hobbies)
		</th>
		<th></th>
	</tr>

@foreach (var item in Model) {
	<tr>
		<td>
			@Html.DisplayFor(modelItem => item.Cedula)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Nombre)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Apellido)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Edad)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Telefono)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Correo)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Genero)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.EstadoCivil)
		</td>
		<td>
			@Html.DisplayFor(modelItem => item.Hobbies)
		</td>
		<td>
			@Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
			@Html.ActionLink("Details", "Details", new { id = item.ID }) |
			@Html.ActionLink("Delete", "Delete", new { id = item.ID })
		</td>
	</tr>
}

</table>

Tarea6/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Tarea6/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Tarea6/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Formulario</h1>
    <p class="lead">Aplicacion de Formulario para datos personales para mayores de 15 años</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Formulario</h2>
        <p>
            Llenar el formulario para crear a alguien nuevo en el sistema
        </p>
        <p>@Html.ActionLink("Llenar formulario »", "Create","Formularios",new {area="" },new { @class = "btn btn-default" })</p>
    </div>
    <div class="col-md-4">
        <h2>Administrar</h2>
        <p>
			Ver la lista de personas ingresadas y administrar cada una.
		</p>
        <p>@Html.ActionLink("Ver »","Index","Formularios", new { area = ""},new { @class = "btn btn-default" })</p>
    </div>
    
</div>

Tarea6/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("Personas", "Index", "Formularios")</li>
					<li>@Html.ActionLink("Formulario", "Create", "Formularios")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>